using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TuristickiVodic.Infrastructure.Data;

#nullable disable

namespace TuristickiVodic.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506130000_AddReviewImages")]
    public partial class AddReviewImages : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""ReviewImages"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ReviewId"" integer NOT NULL REFERENCES ""Reviews""(""Id"") ON DELETE CASCADE,
                    ""Url"" character varying(2000) NOT NULL,
                    ""AltText"" character varying(200),
                    ""CreatedAt"" timestamp with time zone NOT NULL
                );
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_ReviewImages_ReviewId""
                ON ""ReviewImages"" (""ReviewId"");
            ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""ReviewImages"";");
        }
    }
}
