// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TuristickiVodic.Infrastructure.Data;

#nullable disable

namespace TuristickiVodic.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TuristickiVodic.Core.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("DestinationId")
                        .HasColumnType("integer");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Point>("Geolocation")
                        .HasColumnType("geometry");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("LocalityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("ObjectId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActivityTypeId");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("Geolocation");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geolocation"), "GIST");

                    b.HasIndex("LocalityId");

                    b.HasIndex("ObjectId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.ActivityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("ActivityTypes");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.BrowserPushSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ExpirationTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Language")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("BrowserPushSubscriptions");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.DeletionRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EventId")
                        .HasColumnType("integer");

                    b.Property<int?>("ObjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId")
                        .IsUnique()
                        .HasFilter("\"ActivityId\" IS NOT NULL AND \"Status\" = 'Pending'");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasFilter("\"EventId\" IS NOT NULL AND \"Status\" = 'Pending'");

                    b.HasIndex("ObjectId")
                        .IsUnique()
                        .HasFilter("\"ObjectId\" IS NOT NULL AND \"Status\" = 'Pending'");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("ReviewedByUserId");

                    b.ToTable("DeletionRequests", t =>
                        {
                            t.HasCheckConstraint("CK_DeletionRequest_OnlyOne", "(CASE WHEN \"ObjectId\" IS NOT NULL THEN 1 ELSE 0 END +\r\n                   CASE WHEN \"EventId\" IS NOT NULL THEN 1 ELSE 0 END +\r\n                   CASE WHEN \"ActivityId\" IS NOT NULL THEN 1 ELSE 0 END) = 1");
                        });
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Geometry>("Boundary")
                        .HasColumnType("geometry");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DestinationTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayTitle")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime?>("EditLockAcquiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EditLockExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EditLockedByUserId")
                        .HasColumnType("integer");

                    b.Property<Point>("Geolocation")
                        .HasColumnType("geometry");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("ManagedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Boundary");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "GIST");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DestinationTypeId");

                    b.HasIndex("EditLockExpiresAtUtc");

                    b.HasIndex("EditLockedByUserId");

                    b.HasIndex("Geolocation");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geolocation"), "GIST");

                    b.HasIndex("ManagedByUserId")
                        .IsUnique();

                    b.HasIndex("RegionId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.DestinationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("DestinationTypes");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("DestinationId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("integer");

                    b.Property<Point>("Geolocation")
                        .HasColumnType("geometry");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("LocalityId")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxVisitors")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ObjectId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("LocalityId");

                    b.HasIndex("ObjectId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.EventPlannerItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId", "EventId")
                        .IsUnique();

                    b.ToTable("EventPlannerItems");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.EventTicketType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "SortOrder")
                        .IsUnique();

                    b.ToTable("EventTicketTypes");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.EventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("EventTypes");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DestinationId")
                        .HasColumnType("integer");

                    b.Property<int?>("LocalityId")
                        .HasColumnType("integer");

                    b.Property<int?>("ObjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("RouteId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("LocalityId");

                    b.HasIndex("ObjectId");

                    b.HasIndex("RouteId");

                    b.HasIndex("UserId", "ActivityId")
                        .IsUnique()
                        .HasFilter("\"ActivityId\" IS NOT NULL");

                    b.HasIndex("UserId", "DestinationId")
                        .IsUnique()
                        .HasFilter("\"DestinationId\" IS NOT NULL");

                    b.HasIndex("UserId", "LocalityId")
                        .IsUnique()
                        .HasFilter("\"LocalityId\" IS NOT NULL");

                    b.HasIndex("UserId", "ObjectId")
                        .IsUnique()
                        .HasFilter("\"ObjectId\" IS NOT NULL");

                    b.HasIndex("UserId", "RouteId")
                        .IsUnique()
                        .HasFilter("\"RouteId\" IS NOT NULL");

                    b.ToTable("Favorites", t =>
                        {
                            t.HasCheckConstraint("CK_Favorite_OnlyOne", "(CASE WHEN \"ObjectId\" IS NOT NULL THEN 1 ELSE 0 END +\r\n                   CASE WHEN \"ActivityId\" IS NOT NULL THEN 1 ELSE 0 END +\r\n                   CASE WHEN \"DestinationId\" IS NOT NULL THEN 1 ELSE 0 END +\r\n                   CASE WHEN \"RouteId\" IS NOT NULL THEN 1 ELSE 0 END +\r\n                   CASE WHEN \"LocalityId\" IS NOT NULL THEN 1 ELSE 0 END) = 1");
                        });
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityId")
                        .HasColumnType("integer");

                    b.Property<string>("AltText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DestinationId")
                        .HasColumnType("integer");

                    b.Property<int?>("EventId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<int?>("LocalityId")
                        .HasColumnType("integer");

                    b.Property<int?>("ObjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId", "IsMain")
                        .IsUnique()
                        .HasDatabaseName("IX_Images_ActivityId_IsMain_MainUnique")
                        .HasFilter("\"ActivityId\" IS NOT NULL AND \"IsMain\" = TRUE");

                    b.HasIndex("DestinationId", "IsMain")
                        .IsUnique()
                        .HasDatabaseName("IX_Images_DestinationId_IsMain_MainUnique")
                        .HasFilter("\"DestinationId\" IS NOT NULL AND \"IsMain\" = TRUE");

                    b.HasIndex("EventId", "IsMain")
                        .IsUnique()
                        .HasDatabaseName("IX_Images_EventId_IsMain_MainUnique")
                        .HasFilter("\"EventId\" IS NOT NULL AND \"IsMain\" = TRUE");

                    b.HasIndex("LocalityId", "IsMain")
                        .IsUnique()
                        .HasDatabaseName("IX_Images_LocalityId_IsMain_MainUnique")
                        .HasFilter("\"LocalityId\" IS NOT NULL AND \"IsMain\" = TRUE");

                    b.HasIndex("ObjectId", "IsMain")
                        .IsUnique()
                        .HasDatabaseName("IX_Images_ObjectId_IsMain_MainUnique")
                        .HasFilter("\"ObjectId\" IS NOT NULL AND \"IsMain\" = TRUE");

                    b.ToTable("Images", t =>
                        {
                            t.HasCheckConstraint("CK_Image_OnlyOne", "(CASE WHEN \"ObjectId\" IS NOT NULL THEN 1 ELSE 0 END +\r\n                   CASE WHEN \"ActivityId\" IS NOT NULL THEN 1 ELSE 0 END +\r\n                   CASE WHEN \"EventId\" IS NOT NULL THEN 1 ELSE 0 END +\r\n                   CASE WHEN \"DestinationId\" IS NOT NULL THEN 1 ELSE 0 END +\r\n                   CASE WHEN \"LocalityId\" IS NOT NULL THEN 1 ELSE 0 END) = 1");
                        });
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.Language", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.Locality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Geometry>("Boundary")
                        .HasColumnType("geometry");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DestinationId")
                        .HasColumnType("integer");

                    b.Property<Point>("Geolocation")
                        .HasColumnType("geometry");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LocalityTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Boundary");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "GIST");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("Geolocation");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geolocation"), "GIST");

                    b.HasIndex("LocalityTypeId");

                    b.ToTable("Localities");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.LocalityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("LocalityTypes");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.ManagerReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ManagerId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<int>("ReportedUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ResolvedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("ReportedUserId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 0");

                    b.HasIndex("ResolvedByUserId");

                    b.ToTable("ManagerReports");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EventId")
                        .HasColumnType("integer");

                    b.Property<int?>("EventPlannerItemId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReviewId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("TriggerAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("EventPlannerItemId");

                    b.HasIndex("ReviewId");

                    b.HasIndex("UserId", "IsRead", "CreatedAt");

                    b.HasIndex("UserId", "Type", "EventPlannerItemId", "TriggerAtUtc")
                        .IsUnique()
                        .HasFilter("\"EventPlannerItemId\" IS NOT NULL AND \"TriggerAtUtc\" IS NOT NULL");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.ObjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("ObjectTypes");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RememberMe")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Geometry>("Boundary")
                        .HasColumnType("geometry");

                    b.Property<double?>("CenterLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("CenterLongitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DefaultMapZoom")
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Boundary");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "GIST");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasFilter("\"IsDefault\" = TRUE");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatorResponse")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatorResponseAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ObjectId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ObjectId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("UserId", "ObjectId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.ReviewImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReviewId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("ReviewImages");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.RevokedToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Jti")
                        .IsUnique();

                    b.ToTable("RevokedTokens");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("LengthKm")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.RoutePoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Geolocation")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<short>("Order")
                        .HasColumnType("smallint");

                    b.Property<string>("PointName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RouteId", "Order")
                        .IsUnique();

                    b.ToTable("RoutePoints");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.TouristObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.PrimitiveCollection<string[]>("Amenities")
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("CuisineType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DestinationId")
                        .HasColumnType("integer");

                    b.Property<Point>("Geolocation")
                        .HasColumnType("geometry");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("LocalityId")
                        .HasColumnType("integer");

                    b.Property<string>("MenuUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ObjectTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("WorkingHours")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("Geolocation");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geolocation"), "GIST");

                    b.HasIndex("LocalityId");

                    b.HasIndex("ObjectTypeId");

                    b.ToTable("Objects");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAutoTranslated")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalTextHash")
                        .HasColumnType("text");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("TranslatedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId");

                    b.HasIndex("EntityType", "EntityId", "FieldName", "LanguageCode")
                        .IsUnique();

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowPushNotifications")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("BanExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BanReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("BannedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatorRoleRequestStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EditLockAcquiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EditLockExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EditLockedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("HasRequestedCreatorRole")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBlacklisted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<Point>("LastKnownLocation")
                        .HasColumnType("geometry");

                    b.Property<double?>("LastLocationAccuracyMeters")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastLocationUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ManagedDestinationId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("PreferredRegionId")
                        .HasColumnType("integer");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TwoFactorChallengeExpiryUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TwoFactorChallengeTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("TwoFactorCodeExpiryUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TwoFactorCodeHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool?>("TwoFactorRememberMe")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VerificationTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EditLockExpiresAtUtc");

                    b.HasIndex("EditLockedByUserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LastKnownLocation");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("LastKnownLocation"), "GIST");

                    b.HasIndex("PreferredRegionId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.UserLocationHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("AccuracyMeters")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("HeadingDegrees")
                        .HasColumnType("double precision");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("SpeedMetersPerSecond")
                        .HasColumnType("double precision");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("UserId", "RecordedAt");

                    b.ToTable("UserLocationHistories");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.UserLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("ObjectId")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ObjectId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogs", t =>
                        {
                            t.HasCheckConstraint("CK_UserLog_UserOrSession", "\"UserId\" IS NOT NULL OR \"SessionId\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.Activity", b =>
                {
                    b.HasOne("TuristickiVodic.Core.Models.ActivityType", "ActivityType")
                        .WithMany("Activities")
                        .HasForeignKey("ActivityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuristickiVodic.Core.Models.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId");

                    b.HasOne("TuristickiVodic.Core.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TuristickiVodic.Core.Models.Destination", "Destination")
                        .WithMany("Activities")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TuristickiVodic.Core.Models.Locality", "Locality")
                        .WithMany("Activities")
                        .HasForeignKey("LocalityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TuristickiVodic.Core.Models.TouristObject", "Object")
                        .WithMany("Activities")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActivityType");

                    b.Navigation("ApprovedBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("Destination");

                    b.Navigation("Locality");

                    b.Navigation("Object");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.BrowserPushSubscription", b =>
                {
                    b.HasOne("TuristickiVodic.Core.Models.User", "User")
                        .WithMany("BrowserPushSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.DeletionRequest", b =>
                {
                    b.HasOne("TuristickiVodic.Core.Models.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TuristickiVodic.Core.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TuristickiVodic.Core.Models.TouristObject", "Object")
                        .WithMany()
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TuristickiVodic.Core.Models.User", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TuristickiVodic.Core.Models.User", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Activity");

                    b.Navigation("Event");

                    b.Navigation("Object");

                    b.Navigation("RequestedBy");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.Destination", b =>
                {
                    b.HasOne("TuristickiVodic.Core.Models.User", "CreatedBy")
                        .WithMany("CreatedDestinations")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TuristickiVodic.Core.Models.DestinationType", "DestinationType")
                        .WithMany("Destinations")
                        .HasForeignKey("DestinationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuristickiVodic.Core.Models.User", null)
                        .WithMany("LockedDestinations")
                        .HasForeignKey("EditLockedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TuristickiVodic.Core.Models.User", "ManagedBy")
                        .WithOne("ManagedDestination")
                        .HasForeignKey("TuristickiVodic.Core.Models.Destination", "ManagedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TuristickiVodic.Core.Models.Region", "Region")
                        .WithMany("Destinations")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("DestinationType");

                    b.Navigation("ManagedBy");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.Event", b =>
                {
                    b.HasOne("TuristickiVodic.Core.Models.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TuristickiVodic.Core.Models.User", "CreatedBy")
                        .WithMany("CreatedEvents")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TuristickiVodic.Core.Models.Destination", "Destination")
                        .WithMany("Events")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TuristickiVodic.Core.Models.EventType", "EventType")
                        .WithMany("Events")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuristickiVodic.Core.Models.Locality", "Locality")
                        .WithMany("Events")
                        .HasForeignKey("LocalityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TuristickiVodic.Core.Models.TouristObject", "Object")
                        .WithMany("Events")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApprovedBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("Destination");

                    b.Navigation("EventType");

                    b.Navigation("Locality");

                    b.Navigation("Object");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.EventPlannerItem", b =>
                {
                    b.HasOne("TuristickiVodic.Core.Models.Event", "Event")
                        .WithMany("EventPlannerItems")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuristickiVodic.Core.Models.User", "User")
                        .WithMany("EventPlannerItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.EventTicketType", b =>
                {
                    b.HasOne("TuristickiVodic.Core.Models.Event", "Event")
                        .WithMany("TicketTypes")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.Favorite", b =>
                {
                    b.HasOne("TuristickiVodic.Core.Models.Activity", "Activity")
                        .WithMany("Favorites")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TuristickiVodic.Core.Models.Destination", "Destination")
                        .WithMany("Favorites")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TuristickiVodic.Core.Models.Locality", "Locality")
                        .WithMany("Favorites")
                        .HasForeignKey("LocalityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TuristickiVodic.Core.Models.TouristObject", "Object")
                        .WithMany("Favorites")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TuristickiVodic.Core.Models.Route", "Route")
                        .WithMany("Favorites")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TuristickiVodic.Core.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Destination");

                    b.Navigation("Locality");

                    b.Navigation("Object");

                    b.Navigation("Route");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.Image", b =>
                {
                    b.HasOne("TuristickiVodic.Core.Models.Activity", "Activity")
                        .WithMany("Images")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TuristickiVodic.Core.Models.Destination", "Destination")
                        .WithMany("Images")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TuristickiVodic.Core.Models.Event", "Event")
                        .WithMany("Images")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TuristickiVodic.Core.Models.Locality", "Locality")
                        .WithMany("Images")
                        .HasForeignKey("LocalityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TuristickiVodic.Core.Models.TouristObject", "Object")
                        .WithMany("Images")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Activity");

                    b.Navigation("Destination");

                    b.Navigation("Event");

                    b.Navigation("Locality");

                    b.Navigation("Object");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.Locality", b =>
                {
                    b.HasOne("TuristickiVodic.Core.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TuristickiVodic.Core.Models.Destination", "Destination")
                        .WithMany("Localities")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuristickiVodic.Core.Models.LocalityType", "LocalityType")
                        .WithMany("Localities")
                        .HasForeignKey("LocalityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Destination");

                    b.Navigation("LocalityType");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.ManagerReport", b =>
                {
                    b.HasOne("TuristickiVodic.Core.Models.User", "Manager")
                        .WithMany("SentReports")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TuristickiVodic.Core.Models.User", "ReportedUser")
                        .WithMany()
                        .HasForeignKey("ReportedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TuristickiVodic.Core.Models.User", "ResolvedBy")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Manager");

                    b.Navigation("ReportedUser");

                    b.Navigation("ResolvedBy");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.Notification", b =>
                {
                    b.HasOne("TuristickiVodic.Core.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TuristickiVodic.Core.Models.EventPlannerItem", "EventPlannerItem")
                        .WithMany()
                        .HasForeignKey("EventPlannerItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TuristickiVodic.Core.Models.Review", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TuristickiVodic.Core.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("EventPlannerItem");

                    b.Navigation("Review");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.RefreshToken", b =>
                {
                    b.HasOne("TuristickiVodic.Core.Models.User", "User")
                        .WithOne("RefreshToken")
                        .HasForeignKey("TuristickiVodic.Core.Models.RefreshToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.Review", b =>
                {
                    b.HasOne("TuristickiVodic.Core.Models.TouristObject", "Object")
                        .WithMany("Reviews")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuristickiVodic.Core.Models.User", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TuristickiVodic.Core.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Object");

                    b.Navigation("ReviewedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.ReviewImage", b =>
                {
                    b.HasOne("TuristickiVodic.Core.Models.Review", "Review")
                        .WithMany("Images")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.Route", b =>
                {
                    b.HasOne("TuristickiVodic.Core.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.RoutePoint", b =>
                {
                    b.HasOne("TuristickiVodic.Core.Models.Route", "Route")
                        .WithMany("RoutePoints")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.TouristObject", b =>
                {
                    b.HasOne("TuristickiVodic.Core.Models.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TuristickiVodic.Core.Models.User", "CreatedBy")
                        .WithMany("CreatedObjects")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TuristickiVodic.Core.Models.Destination", "Destination")
                        .WithMany("Objects")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuristickiVodic.Core.Models.Locality", "Locality")
                        .WithMany("Objects")
                        .HasForeignKey("LocalityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TuristickiVodic.Core.Models.ObjectType", "ObjectType")
                        .WithMany("Objects")
                        .HasForeignKey("ObjectTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("Destination");

                    b.Navigation("Locality");

                    b.Navigation("ObjectType");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.User", b =>
                {
                    b.HasOne("TuristickiVodic.Core.Models.User", "EditLockedByUser")
                        .WithMany("LockedUsers")
                        .HasForeignKey("EditLockedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TuristickiVodic.Core.Models.Region", "PreferredRegion")
                        .WithMany("PreferredByUsers")
                        .HasForeignKey("PreferredRegionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TuristickiVodic.Core.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EditLockedByUser");

                    b.Navigation("PreferredRegion");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.UserLocationHistory", b =>
                {
                    b.HasOne("TuristickiVodic.Core.Models.User", "User")
                        .WithMany("LocationHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.UserLog", b =>
                {
                    b.HasOne("TuristickiVodic.Core.Models.TouristObject", "Object")
                        .WithMany()
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TuristickiVodic.Core.Models.User", "User")
                        .WithMany("UserLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Object");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.Activity", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.ActivityType", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.Destination", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Events");

                    b.Navigation("Favorites");

                    b.Navigation("Images");

                    b.Navigation("Localities");

                    b.Navigation("Objects");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.DestinationType", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.Event", b =>
                {
                    b.Navigation("EventPlannerItems");

                    b.Navigation("Images");

                    b.Navigation("TicketTypes");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.EventType", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.Locality", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Events");

                    b.Navigation("Favorites");

                    b.Navigation("Images");

                    b.Navigation("Objects");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.LocalityType", b =>
                {
                    b.Navigation("Localities");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.ObjectType", b =>
                {
                    b.Navigation("Objects");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.Region", b =>
                {
                    b.Navigation("Destinations");

                    b.Navigation("PreferredByUsers");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.Review", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.Route", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("RoutePoints");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.TouristObject", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Events");

                    b.Navigation("Favorites");

                    b.Navigation("Images");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("TuristickiVodic.Core.Models.User", b =>
                {
                    b.Navigation("BrowserPushSubscriptions");

                    b.Navigation("CreatedDestinations");

                    b.Navigation("CreatedEvents");

                    b.Navigation("CreatedObjects");

                    b.Navigation("EventPlannerItems");

                    b.Navigation("Favorites");

                    b.Navigation("LocationHistory");

                    b.Navigation("LockedDestinations");

                    b.Navigation("LockedUsers");

                    b.Navigation("ManagedDestination");

                    b.Navigation("Notifications");

                    b.Navigation("RefreshToken");

                    b.Navigation("Reviews");

                    b.Navigation("SentReports");

                    b.Navigation("UserLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
